package com.ejemplo.modelo;
// Generated 22/03/2023 11:28:18 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SDept generated by hbm2java
 */
@Entity
@Table(name = "S_DEPT", schema = "SYSTEM")
public class SDept implements java.io.Serializable {

	private int id;
	private SRegion SRegion;
	private String name;

	public SDept() {
	}

	public SDept(int id, SRegion SRegion, String name) {
		this.id = id;
		this.SRegion = SRegion;
		this.name = name;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 7, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGION_ID", nullable = false)
	public SRegion getSRegion() {
		return this.SRegion;
	}

	public void setSRegion(SRegion SRegion) {
		this.SRegion = SRegion;
	}

	@Column(name = "NAME", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
