package com.ejemplo.modelo;
// Generated 22/03/2023 11:28:18 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SRegion generated by hbm2java
 */
@Entity
@Table(name = "S_REGION", schema = "SYSTEM")
public class SRegion implements java.io.Serializable {

	private int id;
	private String name;
	private Set SDepts = new HashSet(0);

	public SRegion() {
	}

	public SRegion(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public SRegion(int id, String name, Set SDepts) {
		this.id = id;
		this.name = name;
		this.SDepts = SDepts;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 7, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "SRegion")
	public Set getSDepts() {
		return this.SDepts;
	}

	public void setSDepts(Set SDepts) {
		this.SDepts = SDepts;
	}

}
